service: serverless-tutorial-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - comprehend:*
          Resource: "*"

functions:
  analyse:
    handler: lambdas/endpoints/analyse.handler
    events:
      - http:
          path: analyse
          method: POST
          cors: true
