service: serverless-tutorial-project

frameworkVersion: "3"

configValidationMode: "error"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - ses:*
          Resource: "*"

functions:
  sendReminder:
    handler: lambdas/scheduleTasks/reminderEmail.handler
    events:
      - schedule: corn(0 8 ? * * *)
