service: serverless-tutorial-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  environment:
    orderTableName: ${self:custom.orderTableName}
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
            - s3:*
            - ses:*
            - lex:*
          Resource: "*"

package:
  individually: true

custom:
  orderTableName: order-931988

functions:
  telegramToLex:
    handler: lambdas/endpoints/telegramToLex.handler
    events:
      - http:
          path: telegram-webhook
          method: POST
          cors: true

resources:
  Resources:
    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.orderTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
