service: serverless-tutorial-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  environment:
    signupTableName: ${self:custom.signupTableName}
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
            - s3:*
            - ses:*
          Resource: "*"

package:
  individually: true

plugins:
  - serverless-step-functions

custom:
  signupTableName: signup-931988

stepFunctions:
  validate: true
  stateMachines:
    stepFunc1:
      name: reminderEmail
      events:
        - http:
            path: singup-with-reminders
            method: POST
            cors: true
      definition: ${file(./stepFunction.yml)}

functions:
  addSignup:
    handler: lambdas/stepFunctionLambdas/addSignup.handler
  getSignup:
    handler: lambdas/stepFunctionLambdas/getSignup.handler
  sendReminderEmail:
    handler: lambdas/stepFunctionLambdas/sendReminderEmail.handler
  nothing:
    handler: lambdas/stepFunctionLambdas/nothing.handler

resources:
  Resources:
    MyEmailSignupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.signupTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
