service: serverless-tutorial-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - sns:SetSMSAttributes
            - sns:Publish
          Resource: "*"

functions:
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
