service: serverless-tutorial-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  environment:
    bucketName: ${self:custom.bucketName}
    imageUploadBucket: ${self:custom.imageUploadBucket}
    region: ${self:provider.region}
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
            - s3:*
            - ses:*
          Resource: "*"

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  bucketName: serverless-tutorial-project-share-931988
  imageUploadBucket: serverless-tutorial-project-image-upload-931988

functions:
  imageUpload:
    handler: lambdas/endpoints/imageUpload.handler
    events:
      - http:
          path: image-upload
          method: POST
          cors: true

resources:
  Resources:
    ShareBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    ImageBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucket}
        AccessControl: PublicRead
